### PR TITLE
Check wallet signature

### LINKED ISSUE #946: Client signature is not validated/used
**Describe the bug**
Clients should be able to sign for their own messages when publishing an asset. Implementation for this feature has been started in ocean.js but no support at the moment in node.

We should allow the users to sign for their assets and use that signature when publishing an asset

### PR DESCRIPTION
**Pull request by giurgiur99**
Fixes #946 

Changes proposed in this PR:

- If users provides a message signature, check it
- keep backward compatibility

### CODE REVIEW

File: src/components/core/handler/ddoHandler.ts [hunk 1]
```diff
@@ -817,6 +809,22 @@ export class ValidateDDOHandler extends CommandHandler {
       const ddoInstance = DDOManager.getDDOClass(task.ddo)
       const validation = await ddoInstance.validate()
 
+      const { ddo, publisherAddress, nonce, signature: signatureFromRequest } = task
+      if (publisherAddress && nonce && signatureFromRequest) {
```
Comment (alexcos20) [inline src/components/core/handler/ddoHandler.ts:813]: address, nonce, signature should be mandatory.

Comment (giurgiur99) [reply src/components/core/handler/ddoHandler.ts:827]: Added configurable behaviour using VALIDATE_UNSIGNED_DDO env var in last commit.

**Review by mariacarmina — APPROVED** [review]
LGTM!
