### PR TITLE
fix rpcs parse on config

### LINKED ISSUE #419: Config - Parsing/reading process.env.RPCS variable can break if wrong JSON format
On the config we're not expecting a wrongly formatted JSON (not handling possible exception). We have :
```
function getSupportedChains(): RPCS {
  if (!process.env.RPCS || !JSON.parse(process.env.RPCS)) {
```
`JSON.parse(process.env.RPCS)` can throw an exception if the JSON is not correctly formatted and it breaks the node (does not start)

Also, it does not build at all (until we explicitly `unset RPCS`) since the dashboard build will also break with a wrong RPCS env setting:

```
211 packages are looking for funding
  run `npm fund` for details
   Linting and checking validity of types  ..
 ⚠ The Next.js plugin was not detected in your ESLint configuration. See https://nextjs.org/docs/basic-features/eslint#migrating-existing-config
 ✓ Linting and checking validity of types    
   ▲ Next.js 14.0.4
   - Environments: .env

 ✓ Creating an optimized production build    
 ✓ Compiled successfully
   Collecting page data  .SyntaxError: Unexpected token , in JSON at position 104
    at JSON.parse (<anonymous>)
    at 4261 (/home/paulo/workspace/OCEAN/ocean-node/dashboard/.next/server/pages/index.js:82:28961)
    at o (/home/paulo/workspace/OCEAN/ocean-node/dashboard/.next/server/webpack-runtime.js:1:127)
    at /home/paulo/workspace/OCEAN/ocean-node/dashboard/.next/server/pages/index.js:82:23521
    at o.a (/home/paulo/workspace/OCEAN/ocean-node/dashboard/.next/server/webpack-runtime.js:1:864)
    at 3877 (/home/paulo/workspace/OCEAN/ocean-node/dashboard/.next/server/pages/index.js:82:23360)
    at o (/home/paulo/workspace/OCEAN/ocean-node/dashboard/.next/server/webpack-runtime.js:1:127)
    at /home/paulo/workspace/OCEAN/ocean-node/dashboard/.next/server/pages/index.js:82:33173
    at o.a (/home/paulo/workspace/OCEAN/ocean-node/dashboard/.next/server/webpack-runtime.js:1:864)
    at 7229 (/home/paulo/workspace/OCEAN/ocean-node/dashboard/.next/server/pages/index.js:82:33059)

> Build error occurred
Error: Failed to collect page data for /
    at /home/paulo/workspace/OCEAN/ocean-node/dashboard/node_modules/next/dist/build/utils.js:1220:15 {
  type: 'Error'
}
```

### PR DESCRIPTION
**Pull request by paulo-ocean**
Fixes #419 .

Changes proposed in this PR:

- fix parsing of RPCS var on config
- minor update on index queue/dashboard (avoid process.env.RPCS)

### CODE REVIEW

File: dashboard/src/components/IndexQueue.tsx [hunk 1]
```diff
@@ -12,10 +12,35 @@ interface QueueItem {
   chainId: string
 }
 
-const rpcs = JSON.parse(process.env.RPCS || '{}')
-
 export default function IndexQueue() {
   const [queue, setQueue] = useState<QueueItem[]>([])
+  const [rpcs, setRPCs] = useState<any>({})
+
+  useEffect(() => {
```
Comment (jamiehewitt15) [inline dashboard/src/components/IndexQueue.tsx:19]: If you want to use the network names from the status endpoint, we should use [networks](https://github.com/oceanprotocol/ocean-node/pull/416/files#diff-706af29220c8f8e9cf54c3a74b6f8c178313c880a38fc4bf87c53d3a820215aeR31) from the admin provider, so that we avoid calling the status endpoint twice. I can implement that on the other PR and then we remove this API call here.

Comment (jamiehewitt15) [reply dashboard/src/components/IndexQueue.tsx:19]: I've merged the other PR now, so you can get these changes from pulling the latest from develop

Comment (paulo-ocean) [reply dashboard/src/components/IndexQueue.tsx:19]: alright, we'll check that then

**Review by jamiehewitt15 — APPROVED** [review]
Looks good to me
