### PR TITLE
Handle stuck jobs on Running phase. Fix scheduling cleanup for c2d jobs orphans

### LINKED ISSUE #988: Scheduler for expired c2d jobs cleanup throws error when invoked
Scheduler for expired c2d jobs cleanup throws error when invoked at every 5 mins (the interval set in the code by default):

It is triggered in cleanup orphans jobs

### PR DESCRIPTION
**Pull request by mariacarmina**
Fixes #988 #980  .

Changes proposed in this PR:

- fix node crash error when unexisting container was trying to be fetched by c2d monitor loop without deleting sqlite before -> in "RunningAlgorithm" phase, added try-catch and set job status back to ConfiguringVolumes step to re-create the container and resume the job lifecycle
- fixed: if the algorithm job gets stuck in "PublishingResults" phase -> delete the job from sqlite
- surround with try-catch scheduler operations of deleting old logs & deleting expired and orphans c2d jobs
- fixed cleanup orphans jobs:  `OCEANNODE:	Error deleting expired jobs: Cannot read properties of undefined (reading 'id')` by passing environment as parameter to `getFinishedJobs()`
Screenshot 2025-07-19 at 13 56 27

### CODE REVIEW

File: src/components/database/C2DDatabase.ts [hunk 1]
```diff
@@ -117,15 +117,19 @@ export class C2DDatabase extends AbstractDatabase {
...
-    const finishedOrExpired: DBComputeJob[] = await this.provider.getFinishedJobs()
-    const envIds: string[] = existingEnvironments.map((env) => {
-      return env.id
-    })
     let cleaned = 0
-    for (const job of finishedOrExpired) {
-      if (job.environment && !envIds.includes(job.environment)) {
-        if (await c2dDatabase.deleteJob(job.jobId)) {
-          cleaned++
+    const envIds: string[] = existingEnvironments
```
Comment (alexcos20) [inline src/components/database/C2DDatabase.ts:121]: this is not working as it should

**Review by alexcos20 — CHANGES_REQUESTED** [review]

File: src/components/database/C2DDatabase.ts (hunk 1 above)
Comment (mariacarmina) [reply src/components/database/C2DDatabase.ts:121]: What do you mean exactly?
The reason why I changed the existing approach to iterate through computeEnvironments is to pass as parameter the environment to this call (which previously threw error `Error deleting expired jobs: Cannot read properties of undefined (reading 'id')`): await this.provider.getFinishedJobs(computeEnvironment).
It runs as expected the cron job at 5 mins when tested locally.

File: src/components/c2d/compute_engine_docker.ts [hunk 2]
```diff
@@ -976,8 +976,15 @@ export class C2DEngineDocker extends C2DEngine {
...
+        try {
+          const algoLogFile =
+            this.getC2DConfig().tempFolder + '/' + job.jobId + '/data/logs/algorithm.log'
+          writeFileSync(algoLogFile, String(e.message))
+        } catch (e) {
+          console.log('Failed to write')
+          console.log(e)
+        }
         await this.db.updateJob(job)
-        await this.cleanupJob(job)
```
Comment (alexcos20) [inline src/components/c2d/compute_engine_docker.ts]: why was this removed?

**Review by alexcos20 — APPROVED** [review]
lgtm
