### PR TITLE
Fix/ Indexer chunk size reduce

### LINKED ISSUE #354: Indexer:   Fix chunk reading
In indexer code, chunk size is always hardcoded.

Move https://github.com/oceanprotocol/ocean-node/blob/develop/src/components/Indexer/crawlerThread.ts#L79 before while on process blocks.
If an RPC call will fail we need to reduce the chunk size, if chunk size is less than 1, make it 1
RPC call success and we do reduce the chunk size -> go back to original quota (reset the chunk size to the original size for the moment)

### PR DESCRIPTION
**Pull request by bogdanfazakas**
Fixes #354 #366 #388 .

Changes proposed in this PR:

- update reduce chunk size logic
- split retrieve and process logic for chunk size reduction
- added lock to loop so we wait util processing certain blocks before starting with new ones(that may start with the same block) 
- refactored the way we used last indexed block inside the indexer thread

### CODE REVIEW

File: src/components/Indexer/crawlerThread.ts [hunk 1]
```diff
@@ -76,36 +78,52 @@ export async function proccesNetworkData(): Promise<void> {
...
+          chunkEvents,
+          signer,
+          provider,
+          rpcDetails.chainId,
+          startBlock,
+          blocksToProcess
+        )
+        updateLastIndexedBlockNumber(processedBlocks.lastBlock)
+        checkNewlyIndexedAssets(processedBlocks.foundEvents)
+        lastIndexedBlock = processedBlocks.lastBlock
```
Comment (paulo-ocean) [inline src/components/Indexer/crawlerThread.ts:118]: hi @bogdanfazakas 
we're still not addressing the issue #366 
if we start from the "problematic" block 5390003 (if your last indexed block is this one or before it), we get stuck forever on that loop. It keeps failing trying to process the same events for the same ddo, and neither we update the block (like move to the next one, neither we discard/add those specific events to a reindex queue and continue with the same block). We need somehow to at least "blacklist" those events (if we don't want to skip the entire block), so we can move forward with the indexing

attaching some logs, they keep repeating forever...
```
{
  component: 'INDEXER',
  moduleName: 'INDEXER',
  level: 'info',
  message: '[INDEXER] => [INDEXER] => network: optimism-sepolia Start block 5390003 network height 10127332',
  timestamp: '2024-04-02 12:26:46'
}
{
  component: 'INDEXER',
  moduleName: 'INDEXER',
  level: 'info',
  message: 'network: optimism-sepolia processing 100 blocks ...',
  timestamp: '2024-04-02 12:26:46'
}
{
  component: 'INDEXER',
  moduleName: 'INDEXER',
  level: 'info',
  message: '[INDEXER] => [INDEXER] => -- DispenserCreated -- triggered for 0xfad7560ade2324a71eb3b45fda16ace97260206254dddd6234bd3e2ec6e469c7',
  timestamp: '2024-04-02 12:26:46'
}
{
  component: 'INDEXER',
  moduleName: 'INDEXER',
  level: 'info',
  message: '[INDEXER] => [INDEXER] => -- MetadataCreated -- triggered for 0xbb9d9380a5e6cdc809f13b8d287223d23dcb8c0f5ffe126341f3fbdb3b22f52e',
  timestamp: '2024-04-02 12:26:46'
}
{
  component: 'INDEXER',
  moduleName: 'INDEXER',
  level: 'info',
  message: 'Decrypting DDO  from network: 11155420 created by: 0x6c957a45C801035d3297d43d0Ce83a237Ec5E0d1 encrypted by: http://127.0.0.1:8001',
  timestamp: '2024-04-02 12:26:46'
}
{
  component: 'CORE',
  moduleName: 'CORE',
  level: 'info',
  message: '[CORE] => Checking received command data for Command "decryptDDO": {\n' +
    '    "transactionId": "0xbb9d9380a5e6cdc809f13b8d287223d23dcb8c0f5ffe126341f3fbdb3b22f52e",\n' +
    '    "chainId": 11155420,\n' +
    '    "decrypterAddress": "0x8F292046bb73595A978F4e7A131b4EBd03A15e8a",\n' +
    '    "dataNftAddress": "0x2f9B116AE4F1e2EC6829Ca4640A042d5Af499e57",\n' +
    '    "signature": "0xa7d73b906e2184df3e051c36b27ebc6eb33b417028219c4bbc478946f10ef55248ffec1c8800c84d383b729751678b07abe20ce9d80eba8a9e207771dfb61e221b",\n' +
    '    "nonce": "1712057206819",\n' +
    '    "command": "decryptDDO"\n' +
    '}',
  timestamp: '2024-04-02 12:26:46'
}
{
  component: 'DATABASE',
  moduleName: 'DATABASE',
  level: 'error',
  message: '[DATABASE] => ❌ [DATABASE] => Error when retrieving nonce entry for address 0x8F292046bb73595A978F4e7A131b4EBd03A15e8a: Could not find a document with id: 0x8F292046bb73595A978F4e7A131b4EBd03A15e8a',
  timestamp: '2024-04-02 12:26:46'
}
{
  component: 'CORE',
  moduleName: 'CORE',
  level: 'info',
  message: '[CORE] => [CORE] => Decrypt DDO: error Error: Point of length 65 was invalid. Expected 33 compressed bytes or 65 uncompressed bytes',
  timestamp: '2024-04-02 12:26:47'
}
{
  component: 'INDEXER',
  moduleName: 'INDEXER',
  level: 'error',
  message: 'Provider exception on decrypt DDO. Status: Request failed with status code 400',
  timestamp: '2024-04-02 12:26:47'
}
{
  component: 'INDEXER',
  moduleName: 'INDEXER',
  level: 'error',
  message: '[INDEXER] => Error processMetadataEvents: Error: Provider exception on decrypt DDO. Status: Request failed with status code 400',
  timestamp: '2024-04-02 12:26:47'
}
{
  component: 'INDEXER',
  moduleName: 'INDEXER',
  level: 'info',
  message: '[INDEXER] => [INDEXER] => -- OrderStarted -- triggered for 0x462b13b5175554b86bc3249ede819c3a3e72269f1bf824328c8d96e2b047d592',
  timestamp: '2024-04-02 12:26:47'
}
{
  component: 'INDEXER',
  moduleName: 'INDEXER',
  level: 'info',
  message: '[INDEXER] => [INDEXER] => Processed new order for service index 0 at 1702582708',
  timestamp: '2024-04-02 12:26:47'
}
{
  component: 'INDEXER',
  moduleName: 'INDEXER',
  level: 'error',
  message: '[INDEXER] => Processing event from network failed network: optimism-sepolia Error:  Error processing chunk of blocks events no such account ',
  timestamp: '2024-04-02 12:26:47'
}
{
  component: 'INDEXER',
  moduleName: 'INDEXER',
  level: 'info',
  message: '[INDEXER] => [INDEXER] => network: optimism-sepolia Start block 5390003 network height 10127348',
  timestamp: '2024-04-02 12:27:17'
}
{
  component: 'INDEXER',
  moduleName: 'INDEXER',
  level: 'info',
  message: 'network: optimism-sepolia processing 100 blocks ...',
  timestamp: '2024-04-02 12:27:17'
}
{
  component: 'INDEXER',
  moduleName: 'INDEXER',
  level: 'info',
  message: '[INDEXER] => [INDEXER] => -- DispenserCreated -- triggered for 0xfad7560ade2324a71eb3b45fda16ace97260206254dddd6234bd3e2ec6e469c7',
  timestamp: '2024-04-02 12:27:18'
}
{
  component: 'INDEXER',
  moduleName: 'INDEXER',
  level: 'info',
  message: '[INDEXER] => [INDEXER] => -- MetadataCreated -- triggered for 0xbb9d9380a5e6cdc809f13b8d287223d23dcb8c0f5ffe126341f3fbdb3b22f52e',
  timestamp: '2024-04-02 12:27:18'
}
{
  component: 'INDEXER',
  moduleName: 'INDEXER',
  level: 'info',
  message: 'Decrypting DDO  from network: 11155420 created by: 0x6c957a45C801035d3297d43d0Ce83a237Ec5E0d1 encrypted by: http://127.0.0.1:8001',
  timestamp: '2024-04-02 12:27:18'
}
{
  component: 'CORE',
  moduleName: 'CORE',
  level: 'info',
  message: '[CORE] => Checking received command data for Command "decryptDDO": {\n' +
    '    "transactionId": "0xbb9d9380a5e6cdc809f13b8d287223d23dcb8c0f5ffe126341f3fbdb3b22f52e",\n' +
    '    "chainId": 11155420,\n' +
    '    "decrypterAddress": "0x8F292046bb73595A978F4e7A131b4EBd03A15e8a",\n' +
    '    "dataNftAddress": "0x2f9B116AE4F1e2EC6829Ca4640A042d5Af499e57",\n' +
    '    "signature": "0xe06d7960cc60698d0c36392c70bd2269be7d8f0d4c418b19c9e3a0a1ece3acc95711a12141f323482f3f2bec9b92c87dfddd859e395aa312493c394be0c07c071c",\n' +
    '    "nonce": "1712057238513",\n' +
    '    "command": "decryptDDO"\n' +
    '}',
  timestamp: '2024-04-02 12:27:18'
}
{
  component: 'CORE',
  moduleName: 'CORE',
  level: 'info',
  message: '[CORE] => [CORE] => Decrypt DDO: error Error: Point of length 65 was invalid. Expected 33 compressed bytes or 65 uncompressed bytes',
  timestamp: '2024-04-02 12:27:19'
}
{
  component: 'INDEXER',
  moduleName: 'INDEXER',
  level: 'error',
  message: 'Provider exception on decrypt DDO. Status: Request failed with status code 400',
  timestamp: '2024-04-02 12:27:19'
}
{
  component: 'INDEXER',
  moduleName: 'INDEXER',
  level: 'error',
  message: '[INDEXER] => Error processMetadataEvents: Error: Provider exception on decrypt DDO. Status: Request failed with status code 400',
  timestamp: '2024-04-02 12:27:19'
}
{
  component: 'INDEXER',
  moduleName: 'INDEXER',
  level: 'info',
  message: '[INDEXER] => [INDEXER] => -- OrderStarted -- triggered for 0x462b13b5175554b86bc3249ede819c3a3e72269f1bf824328c8d96e2b047d592',
  timestamp: '2024-04-02 12:27:19'
}
{
  component: 'INDEXER',
  moduleName: 'INDEXER',
  level: 'info',
  message: '[INDEXER] => [INDEXER] => Processed new order for service index 0 at 1702582708',
  timestamp: '2024-04-02 12:27:19'
}
{
  component: 'INDEXER',
  moduleName: 'INDEXER',
  level: 'error',
  message: '[INDEXER] => Processing event from network failed network: optimism-sepolia Error:  Error processing chunk of blocks events no such account ',
  timestamp: '2024-04-02 12:27:19'
}
TimeoutError: Promise timed out after 60000 milliseconds
    at file:///home/paulo/workspace/OCEAN/ocean-node/node_modules/p-timeout/index.js:70:24
    at new Promise (<anonymous>)
    at pTimeout (file:///home/paulo/workspace/OCEAN/ocean-node/node_modules/p-timeout/index.js:48:25)
    at Object.gateway (file:///home/paulo/workspace/OCEAN/ocean-node/node_modules/@achingbrain/nat-port-mapper/dist/src/discovery/index.js:56:39)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async UPNPClient.findGateway (file:///home/paulo/workspace/OCEAN/ocean-node/node_modules/@achingbrain/nat-port-mapper/dist/src/upnp/index.js:80:25)
    at async UPNPClient.externalIp (file:///home/paulo/workspace/OCEAN/ocean-node/node_modules/@achingbrain/nat-port-mapper/dist/src/upnp/index.js:59:25)
    at async UPnPNAT.mapIpAddresses (file:///home/paulo/workspace/OCEAN/ocean-node/node_modules/@libp2p/upnp-nat/dist/src/upnp-nat.js:78:54)
{
  component: 'INDEXER',
  moduleName: 'INDEXER',
  level: 'info',
  message: '[INDEXER] => [INDEXER] => network: optimism-sepolia Start block 5390003 network height 10127364',
  timestamp: '2024-04-02 12:27:49'
}
{
  component: 'INDEXER',
  moduleName: 'INDEXER',
  level: 'info',
  message: 'network: optimism-sepolia processing 100 blocks ...',
  timestamp: '2024-04-02 12:27:49'
}
{
  component: 'INDEXER',
  moduleName: 'INDEXER',
  level: 'info',
  message: '[INDEXER] => [INDEXER] => -- DispenserCreated -- triggered for 0xfad7560ade2324a71eb3b45fda16ace97260206254dddd6234bd3e2ec6e469c7',
  timestamp: '2024-04-02 12:27:49'
}
{
  component: 'INDEXER',
  moduleName: 'INDEXER',
  level: 'info',
  message: '[INDEXER] => [INDEXER] => -- MetadataCreated -- triggered for 0xbb9d9380a5e6cdc809f13b8d287223d23dcb8c0f5ffe126341f3fbdb3b22f52e',
  timestamp: '2024-04-02 12:27:49'
}
{
  component: 'INDEXER',
  moduleName: 'INDEXER',
  level: 'info',
  message: 'Decrypting DDO  from network: 11155420 created by: 0x6c957a45C801035d3297d43d0Ce83a237Ec5E0d1 encrypted by: http://127.0.0.1:8001',
  timestamp: '2024-04-02 12:27:49'
}
{
  component: 'CORE',
  moduleName: 'CORE',
  level: 'info',
  message: '[CORE] => Checking received command data for Command "decryptDDO": {\n' +
    '    "transactionId": "0xbb9d9380a5e6cdc809f13b8d287223d23dcb8c0f5ffe126341f3fbdb3b22f52e",\n' +
    '    "chainId": 11155420,\n' +
    '    "decrypterAddress": "0x8F292046bb73595A978F4e7A131b4EBd03A15e8a",\n' +
    '    "dataNftAddress": "0x2f9B116AE4F1e2EC6829Ca4640A042d5Af499e57",\n' +
    '    "signature": "0x2a507c156b31ea40d3bb19e4e4fb54c65be57c39efe73145c6a7d08bd07cbdd155ecb184a8a9512773d231abe0a1297f8c1c0099d15a60ef69ecf0162304753a1b",\n' +
    '    "nonce": "1712057269937",\n' +
    '    "command": "decryptDDO"\n' +
    '}',
  timestamp: '2024-04-02 12:27:49'
}
{
  component: 'CORE',
  moduleName: 'CORE',
  level: 'info',
  message: '[CORE] => [CORE] => Decrypt DDO: error Error: Point of length 65 was invalid. Expected 33 compressed bytes or 65 uncompressed bytes',
  timestamp: '2024-04-02 12:27:50'
}
{
  component: 'INDEXER',
  moduleName: 'INDEXER',
  level: 'error',
  message: 'Provider exception on decrypt DDO. Status: Request failed with status code 400',
  timestamp: '2024-04-02 12:27:50'
}
{
  component: 'INDEXER',
  moduleName: 'INDEXER',
  level: 'error',
  message: '[INDEXER] => Error processMetadataEvents: Error: Provider exception on decrypt DDO. Status: Request failed with status code 400',
  timestamp: '2024-04-02 12:27:50'
}
{
  component: 'INDEXER',
  moduleName: 'INDEXER',
  level: 'info',
  message: '[INDEXER] => [INDEXER] => -- OrderStarted -- triggered for 0x462b13b5175554b86bc3249ede819c3a3e72269f1bf824328c8d96e2b047d592',
  timestamp: '2024-04-02 12:27:50'
}
{
  component: 'INDEXER',
  moduleName: 'INDEXER',
  level: 'info',
  message: '[INDEXER] => [INDEXER] => Processed new order for service index 0 at 1702582708',
  timestamp: '2024-04-02 12:27:50'
}
{
  component: 'INDEXER',
  moduleName: 'INDEXER',
  level: 'error',
  message: '[INDEXER] => Processing event from network failed network: optimism-sepolia Error:  Error processing chunk of blocks events no such account ',
  timestamp: '2024-04-02 12:27:50'
}
{
  component: 'INDEXER',
  moduleName: 'INDEXER',
  level: 'info',
  message: '[INDEXER] => [INDEXER] => network: optimism-sepolia Start block 5390003 network height 10127379',
  timestamp: '2024-04-02 12:28:20'
}
{
  component: 'INDEXER',
  moduleName: 'INDEXER',
  level: 'info',
  message: 'network: optimism-sepolia processing 100 blocks ...',
  timestamp: '2024-04-02 12:28:20'
}
{
  component: 'INDEXER',
  moduleName: 'INDEXER',
  level: 'info',
  message: '[INDEXER] => [INDEXER] => -- DispenserCreated -- triggered for 0xfad7560ade2324a71eb3b45fda16ace97260206254dddd6234bd3e2ec6e469c7',
  timestamp: '2024-04-02 12:28:21'
}
{
  component: 'INDEXER',
  moduleName: 'INDEXER',
  level: 'info',
  message: '[INDEXER] => [INDEXER] => -- MetadataCreated -- triggered for 0xbb9d9380a5e6cdc809f13b8d287223d23dcb8c0f5ffe126341f3fbdb3b22f52e',
  timestamp: '2024-04-02 12:28:21'
}
{
  component: 'INDEXER',
  moduleName: 'INDEXER',
  level: 'info',
  message: 'Decrypting DDO  from network: 11155420 created by: 0x6c957a45C801035d3297d43d0Ce83a237Ec5E0d1 encrypted by: http://127.0.0.1:8001',
  timestamp: '2024-04-02 12:28:21'
}
{
  component: 'CORE',
  moduleName: 'CORE',
  level: 'info',
  message: '[CORE] => Checking received command data for Command "decryptDDO": {\n' +
    '    "transactionId": "0xbb9d9380a5e6cdc809f13b8d287223d23dcb8c0f5ffe126341f3fbdb3b22f52e",\n' +
    '    "chainId": 11155420,\n' +
    '    "decrypterAddress": "0x8F292046bb73595A978F4e7A131b4EBd03A15e8a",\n' +
    '    "dataNftAddress": "0x2f9B116AE4F1e2EC6829Ca4640A042d5Af499e57",\n' +
    '    "signature": "0x245b7c88e07155008a135a9c58b1deb2ec9872179befaff8d61323d6d1866e9e744ef234c705d7349fbb36d56bdfcd9e3321ca15266fd08910cc57fb3b10e0d21b",\n' +
    '    "nonce": "1712057301582",\n' +
    '    "command": "decryptDDO"\n' +
    '}',
  timestamp: '2024-04-02 12:28:21'
}
{
  component: 'CORE',
  moduleName: 'CORE',
  level: 'info',
  message: '[CORE] => [CORE] => Decrypt DDO: error Error: Point of length 65 was invalid. Expected 33 compressed bytes or 65 uncompressed bytes',
  timestamp: '2024-04-02 12:28:22'
}
{
  component: 'INDEXER',
  moduleName: 'INDEXER',
  level: 'error',
  message: 'Provider exception on decrypt DDO. Status: Request failed with status code 400',
  timestamp: '2024-04-02 12:28:22'
}
{
  component: 'INDEXER',
  moduleName: 'INDEXER',
  level: 'error',
  message: '[INDEXER] => Error processMetadataEvents: Error: Provider exception on decrypt DDO. Status: Request failed with status code 400',
  timestamp: '2024-04-02 12:28:22'
}
{
  component: 'INDEXER',
  moduleName: 'INDEXER',
  level: 'info',
  message: '[INDEXER] => [INDEXER] => -- OrderStarted -- triggered for 0x462b13b5175554b86bc3249ede819c3a3e72269f1bf824328c8d96e2b047d592',
  timestamp: '2024-04-02 12:28:22'
}
{
  component: 'INDEXER',
  moduleName: 'INDEXER',
  level: 'info',
  message: '[INDEXER] => [INDEXER] => Processed new order for service index 0 at 1702582708',
  timestamp: '2024-04-02 12:28:22'
}
{
  component: 'INDEXER',
  moduleName: 'INDEXER',
  level: 'error',
  message: '[INDEXER] => Processing event from network failed network: optimism-sepolia Error:  Error processing chunk of blocks events no such account ',
  timestamp: '2024-04-02 12:28:22'
}
{
  component: 'INDEXER',
  moduleName: 'INDEXER',
  level: 'info',
  message: '[INDEXER] => [INDEXER] => network: optimism-sepolia Start block 5390003 network height 10127395',
  timestamp: '2024-04-02 12:28:52'
}
{
  component: 'INDEXER',
  moduleName: 'INDEXER',
  level: 'info',
  message: 'network: optimism-sepolia processing 100 blocks ...',
  timestamp: '2024-04-02 12:28:52'
}
{
  component: 'INDEXER',
  moduleName: 'INDEXER',
  level: 'info',
  message: '[INDEXER] => [INDEXER] => -- DispenserCreated -- triggered for 0xfad7560ade2324a71eb3b45fda16ace97260206254dddd6234bd3e2ec6e469c7',
  timestamp: '2024-04-02 12:28:52'
}
{
  component: 'INDEXER',
  moduleName: 'INDEXER',
  level: 'info',
  message: '[INDEXER] => [INDEXER] => -- MetadataCreated -- triggered for 0xbb9d9380a5e6cdc809f13b8d287223d23dcb8c0f5ffe126341f3fbdb3b22f52e',
  timestamp: '2024-04-02 12:28:52'
}
{
  component: 'INDEXER',
  moduleName: 'INDEXER',
  level: 'info',
  message: 'Decrypting DDO  from network: 11155420 created by: 0x6c957a45C801035d3297d43d0Ce83a237Ec5E0d1 encrypted by: http://127.0.0.1:8001',
  timestamp: '2024-04-02 12:28:53'
}
{
  component: 'CORE',
  moduleName: 'CORE',
  level: 'info',
  message: '[CORE] => Checking received command data for Command "decryptDDO": {\n' +
    '    "transactionId": "0xbb9d9380a5e6cdc809f13b8d287223d23dcb8c0f5ffe126341f3fbdb3b22f52e",\n' +
    '    "chainId": 11155420,\n' +
    '    "decrypterAddress": "0x8F292046bb73595A978F4e7A131b4EBd03A15e8a",\n' +
    '    "dataNftAddress": "0x2f9B116AE4F1e2EC6829Ca4640A042d5Af499e57",\n' +
    '    "signature": "0xf48176d2dc4fd48b710d114b7895d7e73a24fb47255efccce3a08059314d7a9e01c63f7c4c47b1f45741aa34ac786676dafbe98f55d05092bf0136520c86c97e1c",\n' +
    '    "nonce": "1712057333106",\n' +
    '    "command": "decryptDDO"\n' +
    '}',
  timestamp: '2024-04-02 12:28:53'
}
{
  component: 'CORE',
  moduleName: 'CORE',
  level: 'info',
  message: '[CORE] => [CORE] => Decrypt DDO: error Error: Point of length 65 was invalid. Expected 33 compressed bytes or 65 uncompressed bytes',
  timestamp: '2024-04-02 12:28:53'
}
{
  component: 'INDEXER',
  moduleName: 'INDEXER',
  level: 'error',
  message: 'Provider exception on decrypt DDO. Status: Request failed with status code 400',
  timestamp: '2024-04-02 12:28:53'
}
{
  component: 'INDEXER',
  moduleName: 'INDEXER',
  level: 'error',
  message: '[INDEXER] => Error processMetadataEvents: Error: Provider exception on decrypt DDO. Status: Request failed with status code 400',
  timestamp: '2024-04-02 12:28:53'
}
{
  component: 'INDEXER',
  moduleName: 'INDEXER',
  level: 'info',
  message: '[INDEXER] => [INDEXER] => -- OrderStarted -- triggered for 0x462b13b5175554b86bc3249ede819c3a3e72269f1bf824328c8d96e2b047d592',
  timestamp: '2024-04-02 12:28:53'
}
{
  component: 'INDEXER',
  moduleName: 'INDEXER',
  level: 'info',
  message: '[INDEXER] => [INDEXER] => Processed new order for service index 0 at 1702582708',
  timestamp: '2024-04-02 12:28:53'
}
{
  component: 'INDEXER',
  moduleName: 'INDEXER',
  level: 'error',
  message: '[INDEXER] => Processing event from network failed network: optimism-sepolia Error:  Error processing chunk of blocks events no such account ',
  timestamp: '2024-04-02 12:28:53'
}

```
tkx

**Comment by bogdanfazakas** [comment]
> hey @bogdanfazakas can you check the integration test "`should store the ddo state in the db with no errors and retrieve it using did`" this seems to be failing since the merge of the "fix ddo state endpoint PR" thanks

yeah checking it now, strange things going on, was not failing on the branch and also the tests are passing locally 😃 
so a bit more to debug

**Comment by paulo-ocean** [comment]
i was actually reviewing this while you were changing it :-)
anyway, just noticed that your `lockProccessing` variable is always `false`, not what you wanted for sure :-)

**Comment by bogdanfazakas** [comment]
@paulo-ocean & @mariacarmina @jamiehewitt15  this should be ready and should fix also our integration test issues

File: src/components/Indexer/crawlerThread.ts [hunk 2]
```diff
@@ -62,52 +80,81 @@ export async function proccesNetworkData(): Promise<void> {
...
+            `Processing event from network failed network: ${rpcDetails.network} Error: ${error.message} `,
+            true
+          )
+          await updateLastIndexedBlockNumber(startBlock + blocksToProcess)
+        }
       }
+      await processReindex()
+      lockProccessing = false
+      INDEXER_LOGGER.logMessage(
+        `Finished processing blocks ${startBlock} to ${indexedBlock} for network ${rpcDetails.network}`,
```
Comment (paulo-ocean) [inline src/components/Indexer/crawlerThread.ts:149]: minor stuff, but you should probably update the value of `indexedBlock = processedBlocks.lastBlock` as it was before, right after the call to `await updateLastIndexedBlockNumber(processedBlocks.lastBlock)`
right now you're updating it only at begiining of the loop:
`const indexedBlock = await getLastIndexedBlock()`
So the logs message at the end do not make much sense,  because the value of `${startBlock}` and `${indexedBlock}` are the same

currently, the sequence of log messages look like this:
1) `New last indexed block : 60',`
2 ) `Finished processing blocks 57 to 57 for network development',`
and should be:
2 ) `Finished processing blocks 57 to **60** for network development',`
thanks

Comment (bogdanfazakas) [reply src/components/Indexer/crawlerThread.ts:149]: I'll just remove that log, i've added more for debug purpose to track certain events, it is somehow redundant since we have started processing from to and the height plus nr of blocks we process, and we also have the case when we log that the processing is already in place so we need to wait and try again

**Review by jamiehewitt15 — APPROVED** [review]
Looks good to me
